/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeblocksIndexRouteImport } from './routes/codeblocks/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as VisualEditorIndexRouteImport } from './routes/visual-editor/index'
import { Route as MarketplacePluginsIndexRouteImport } from './routes/marketplace/plugins/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeblocksIndexRoute = CodeblocksIndexRouteImport.update({
  id: '/codeblocks/',
  path: '/codeblocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualEditorIndexRoute = VisualEditorIndexRouteImport.update({
  id: '/visual-editor/',
  path: '/visual-editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacePluginsIndexRoute = MarketplacePluginsIndexRouteImport.update({
  id: '/marketplace/plugins/',
  path: '/marketplace/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codeblocks/': typeof CodeblocksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/visual-editor/': typeof VisualEditorIndexRoute
  '/marketplace/plugins/': typeof MarketplacePluginsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codeblocks': typeof CodeblocksIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/visual-editor': typeof VisualEditorIndexRoute
  '/marketplace/plugins': typeof MarketplacePluginsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codeblocks/': typeof CodeblocksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/visual-editor/': typeof VisualEditorIndexRoute
  '/marketplace/plugins/': typeof MarketplacePluginsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codeblocks/'
    | '/dashboard/'
    | '/visual-editor/'
    | '/marketplace/plugins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codeblocks'
    | '/dashboard'
    | '/visual-editor'
    | '/marketplace/plugins'
  id:
    | '__root__'
    | '/'
    | '/codeblocks/'
    | '/dashboard/'
    | '/visual-editor/'
    | '/marketplace/plugins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeblocksIndexRoute: typeof CodeblocksIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  VisualEditorIndexRoute: typeof VisualEditorIndexRoute
  MarketplacePluginsIndexRoute: typeof MarketplacePluginsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codeblocks/': {
      id: '/codeblocks/'
      path: '/codeblocks'
      fullPath: '/codeblocks/'
      preLoaderRoute: typeof CodeblocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-editor/': {
      id: '/visual-editor/'
      path: '/visual-editor'
      fullPath: '/visual-editor/'
      preLoaderRoute: typeof VisualEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/plugins/': {
      id: '/marketplace/plugins/'
      path: '/marketplace/plugins'
      fullPath: '/marketplace/plugins/'
      preLoaderRoute: typeof MarketplacePluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeblocksIndexRoute: CodeblocksIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  VisualEditorIndexRoute: VisualEditorIndexRoute,
  MarketplacePluginsIndexRoute: MarketplacePluginsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
