/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuleEngineRouteRouteImport } from './routes/rule-engine/route'
import { Route as ApisIndexRouteImport } from './routes/apis/index'
import { Route as ContextIndexRouteImport } from './routes/context/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as FeatureFlagsIndexRouteImport } from './routes/feature-flags/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as RuleEngineIndexRouteImport } from './routes/rule-engine/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as RuleEngineProjectIdIndexRouteImport } from './routes/rule-engine/$projectId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleEngineRouteRoute = RuleEngineRouteRouteImport.update({
  id: '/rule-engine',
  path: '/rule-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisIndexRoute = ApisIndexRouteImport.update({
  id: '/apis/',
  path: '/apis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextIndexRoute = ContextIndexRouteImport.update({
  id: '/context/',
  path: '/context/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsIndexRoute = FeatureFlagsIndexRouteImport.update({
  id: '/feature-flags/',
  path: '/feature-flags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleEngineIndexRoute = RuleEngineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuleEngineRouteRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleEngineProjectIdIndexRoute =
  RuleEngineProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => RuleEngineRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rule-engine': typeof RuleEngineRouteRouteWithChildren
  '/apis/': typeof ApisIndexRoute
  '/context/': typeof ContextIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rule-engine/': typeof RuleEngineIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/rule-engine/$projectId/': typeof RuleEngineProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apis': typeof ApisIndexRoute
  '/context': typeof ContextIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/feature-flags': typeof FeatureFlagsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/rule-engine': typeof RuleEngineIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/rule-engine/$projectId': typeof RuleEngineProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rule-engine': typeof RuleEngineRouteRouteWithChildren
  '/apis/': typeof ApisIndexRoute
  '/context/': typeof ContextIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rule-engine/': typeof RuleEngineIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/rule-engine/$projectId/': typeof RuleEngineProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rule-engine'
    | '/apis/'
    | '/context/'
    | '/dashboard/'
    | '/feature-flags/'
    | '/projects/'
    | '/rule-engine/'
    | '/projects/$projectId/'
    | '/rule-engine/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apis'
    | '/context'
    | '/dashboard'
    | '/feature-flags'
    | '/projects'
    | '/rule-engine'
    | '/projects/$projectId'
    | '/rule-engine/$projectId'
  id:
    | '__root__'
    | '/'
    | '/rule-engine'
    | '/apis/'
    | '/context/'
    | '/dashboard/'
    | '/feature-flags/'
    | '/projects/'
    | '/rule-engine/'
    | '/projects/$projectId/'
    | '/rule-engine/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RuleEngineRouteRoute: typeof RuleEngineRouteRouteWithChildren
  ApisIndexRoute: typeof ApisIndexRoute
  ContextIndexRoute: typeof ContextIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FeatureFlagsIndexRoute: typeof FeatureFlagsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-engine': {
      id: '/rule-engine'
      path: '/rule-engine'
      fullPath: '/rule-engine'
      preLoaderRoute: typeof RuleEngineRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis/': {
      id: '/apis/'
      path: '/apis'
      fullPath: '/apis/'
      preLoaderRoute: typeof ApisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context/': {
      id: '/context/'
      path: '/context'
      fullPath: '/context/'
      preLoaderRoute: typeof ContextIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags/': {
      id: '/feature-flags/'
      path: '/feature-flags'
      fullPath: '/feature-flags/'
      preLoaderRoute: typeof FeatureFlagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-engine/': {
      id: '/rule-engine/'
      path: '/'
      fullPath: '/rule-engine/'
      preLoaderRoute: typeof RuleEngineIndexRouteImport
      parentRoute: typeof RuleEngineRouteRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-engine/$projectId/': {
      id: '/rule-engine/$projectId/'
      path: '/$projectId'
      fullPath: '/rule-engine/$projectId/'
      preLoaderRoute: typeof RuleEngineProjectIdIndexRouteImport
      parentRoute: typeof RuleEngineRouteRoute
    }
  }
}

interface RuleEngineRouteRouteChildren {
  RuleEngineIndexRoute: typeof RuleEngineIndexRoute
  RuleEngineProjectIdIndexRoute: typeof RuleEngineProjectIdIndexRoute
}

const RuleEngineRouteRouteChildren: RuleEngineRouteRouteChildren = {
  RuleEngineIndexRoute: RuleEngineIndexRoute,
  RuleEngineProjectIdIndexRoute: RuleEngineProjectIdIndexRoute,
}

const RuleEngineRouteRouteWithChildren = RuleEngineRouteRoute._addFileChildren(
  RuleEngineRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RuleEngineRouteRoute: RuleEngineRouteRouteWithChildren,
  ApisIndexRoute: ApisIndexRoute,
  ContextIndexRoute: ContextIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FeatureFlagsIndexRoute: FeatureFlagsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
