/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardApisIndexRouteImport } from './routes/dashboard/apis/index'
import { Route as DashboardContextIndexRouteImport } from './routes/dashboard/context/index'
import { Route as DashboardFeatureFlagsIndexRouteImport } from './routes/dashboard/feature-flags/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardRuleEngineIndexRouteImport } from './routes/dashboard/rule-engine/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApisIndexRoute = DashboardApisIndexRouteImport.update({
  id: '/apis/',
  path: '/apis/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContextIndexRoute = DashboardContextIndexRouteImport.update({
  id: '/context/',
  path: '/context/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFeatureFlagsIndexRoute =
  DashboardFeatureFlagsIndexRouteImport.update({
    id: '/feature-flags/',
    path: '/feature-flags/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRuleEngineIndexRoute =
  DashboardRuleEngineIndexRouteImport.update({
    id: '/rule-engine/',
    path: '/rule-engine/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/apis/': typeof DashboardApisIndexRoute
  '/dashboard/context/': typeof DashboardContextIndexRoute
  '/dashboard/feature-flags/': typeof DashboardFeatureFlagsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/rule-engine/': typeof DashboardRuleEngineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/apis': typeof DashboardApisIndexRoute
  '/dashboard/context': typeof DashboardContextIndexRoute
  '/dashboard/feature-flags': typeof DashboardFeatureFlagsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/rule-engine': typeof DashboardRuleEngineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/apis/': typeof DashboardApisIndexRoute
  '/dashboard/context/': typeof DashboardContextIndexRoute
  '/dashboard/feature-flags/': typeof DashboardFeatureFlagsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/rule-engine/': typeof DashboardRuleEngineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/apis/'
    | '/dashboard/context/'
    | '/dashboard/feature-flags/'
    | '/dashboard/projects/'
    | '/dashboard/rule-engine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/apis'
    | '/dashboard/context'
    | '/dashboard/feature-flags'
    | '/dashboard/projects'
    | '/dashboard/rule-engine'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/apis/'
    | '/dashboard/context/'
    | '/dashboard/feature-flags/'
    | '/dashboard/projects/'
    | '/dashboard/rule-engine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/apis/': {
      id: '/dashboard/apis/'
      path: '/apis'
      fullPath: '/dashboard/apis/'
      preLoaderRoute: typeof DashboardApisIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/context/': {
      id: '/dashboard/context/'
      path: '/context'
      fullPath: '/dashboard/context/'
      preLoaderRoute: typeof DashboardContextIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/feature-flags/': {
      id: '/dashboard/feature-flags/'
      path: '/feature-flags'
      fullPath: '/dashboard/feature-flags/'
      preLoaderRoute: typeof DashboardFeatureFlagsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rule-engine/': {
      id: '/dashboard/rule-engine/'
      path: '/rule-engine'
      fullPath: '/dashboard/rule-engine/'
      preLoaderRoute: typeof DashboardRuleEngineIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApisIndexRoute: typeof DashboardApisIndexRoute
  DashboardContextIndexRoute: typeof DashboardContextIndexRoute
  DashboardFeatureFlagsIndexRoute: typeof DashboardFeatureFlagsIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardRuleEngineIndexRoute: typeof DashboardRuleEngineIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApisIndexRoute: DashboardApisIndexRoute,
  DashboardContextIndexRoute: DashboardContextIndexRoute,
  DashboardFeatureFlagsIndexRoute: DashboardFeatureFlagsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardRuleEngineIndexRoute: DashboardRuleEngineIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
